"""HELLFORGE safe update — update the core version WITHOUT losing anything.

Preserved across updates:
  - custom plugins in plugins/ (dirs not shipped by upstream)
  - mods/
  - config: .plugin_config.json, .env, .e_identity/
  - local manifest extension (SECURITY_HASH.local)
  - any uncommitted work (stashed, then restored)

Update = git fetch origin + checkout of the target tag, then restore the
user data and re-register custom plugins in the local manifest extension.
"""

import json
import os
import shutil
import subprocess
from pathlib import Path

from . import security_hash as SH

PROJECT_DIR = SH.PROJECT_DIR
BACKUP_DIR = PROJECT_DIR / ".backup_update"

PROTECTED = (".plugin_config.json", ".env", ".e_identity", "mods",
             "SECURITY_HASH.local")


def _git(args, timeout=120):
    r = subprocess.run(["git"] + args, capture_output=True, text=True,
                       timeout=timeout, cwd=str(PROJECT_DIR))
    return r.returncode, (r.stdout + r.stderr).strip()


def _shipped_plugins():
    """Plugin dirs shipped by the upstream manifest (committed)."""
    m, _ = SH.load_committed()
    shipped = set()
    if m:
        for rel in m:
            if rel.startswith("plugins/") and rel.endswith("/__init__.py"):
                shipped.add(rel.split("/")[1])
    return shipped


def custom_plugins():
    """Plugin dirs that exist locally but are NOT shipped upstream."""
    shipped = _shipped_plugins()
    out = []
    plugs = PROJECT_DIR / "plugins"
    if plugs.is_dir():
        for d in sorted(plugs.iterdir()):
            if d.is_dir() and d.name != "__pycache__" and d.name not in shipped:
                out.append(d.name)
    return out


def backup_user_data(progress=None):
    """Copy user data out of the way. Returns the backup dir."""
    if BACKUP_DIR.exists():
        shutil.rmtree(BACKUP_DIR)
    BACKUP_DIR.mkdir(parents=True)
    for name in PROTECTED:
        src = PROJECT_DIR / name
        if src.exists():
            dst = BACKUP_DIR / name
            if src.is_dir():
                shutil.copytree(src, dst)
            else:
                shutil.copy2(src, dst)
    # custom plugin dirs
    for name in custom_plugins():
        src = PROJECT_DIR / "plugins" / name
        shutil.copytree(src, BACKUP_DIR / "plugins" / name)
    if progress:
        progress(20)
    return BACKUP_DIR


def restore_user_data(progress=None):
    """Put user data back after the checkout."""
    for name in PROTECTED:
        src = BACKUP_DIR / name
        if not src.exists():
            continue
        dst = PROJECT_DIR / name
        if dst.exists():
            if dst.is_dir():
                shutil.rmtree(dst)
            else:
                dst.unlink()
        if src.is_dir():
            shutil.copytree(src, dst)
        else:
            shutil.copy2(src, dst)
    # custom plugins back
    bplug = BACKUP_DIR / "plugins"
    if bplug.is_dir():
        for d in bplug.iterdir():
            dst = PROJECT_DIR / "plugins" / d.name
            if dst.exists():
                shutil.rmtree(dst)
            shutil.copytree(d, dst)
    if progress:
        progress(30)


def register_custom_plugins(progress=None):
    """Extend the local manifest (SECURITY_HASH.local) with custom plugins
    so the digest check accepts them."""
    from . import security_hash as SHm
    manifest = SHm.compute_manifest()
    # only the custom plugin entries
    custom = {}
    shipped = _shipped_plugins()
    for rel, h in sorted(manifest.items()):
        if rel.startswith("plugins/"):
            name = rel.split("/")[1]
            if name not in shipped:
                custom[rel] = h
    if not custom:
        return
    lines = ["# HELLFORGE local manifest extension — custom plugins.",
             "# Regenerated by the updater after each update."]
    for rel, h in sorted(custom.items()):
        lines.append(f"{rel}:{h}")
    (PROJECT_DIR / "SECURITY_HASH.local").write_text("\n".join(lines) + "\n")
    if progress:
        progress(40)


def safe_update(target_tag, progress=None, stream_out=print):
    """Update to a version tag, preserving everything. Returns exit code."""
    def step(n):
        if progress:
            progress(n)

    stream_out(f"  updating to {target_tag} — backing up your data first...")
    backup_user_data(step)

    # K-rip kernel registry: the current kernel becomes a bootable previous
    try:
        from plugins.krip import snapshot_previous_kernel
        snapshot_previous_kernel()
    except Exception:
        pass

    stream_out("  fetching from GitHub...")
    rc, err = _git(["fetch", "origin", "tag", target_tag])
    if rc != 0:
        stream_out(f"  fetch failed: {err}")
        return 1
    step(60)

    # stash uncommitted work (restored afterwards)
    rc, err = _git(["stash", "push", "-u", "-m", "hellgate-update"])
    had_stash = rc == 0
    step(65)

    stream_out(f"  checking out {target_tag}...")
    rc, err = _git(["checkout", "-f", target_tag])
    if rc != 0:
        stream_out(f"  checkout failed: {err}")
        if had_stash:
            _git(["stash", "pop"])
        return 1
    step(75)

    restore_user_data(step)
    register_custom_plugins(step)

    if had_stash:
        rc, err = _git(["stash", "pop"])
        if rc != 0:
            stream_out(f"  warning: could not restore stashed work: {err}")
    step(90)

    # fresh X + Y layout + integrity re-check
    try:
        from ep_compiler.security_hash import (digest_bundle, compute_manifest,
                                               load_version_key, x_embed)
        tag, key = load_version_key()
        x_embed(digest_bundle(compute_manifest()), key or "")
    except Exception:
        pass
    step(100)
    stream_out(f"  update complete: {target_tag}")
    return 0


def current_target():
    """The version tag to (re)install: latest remote or current local."""
    latest = SH.remote_version()
    return latest or SH.local_version()
